In [1]:
import sqlite3
import pandas as pd

In [2]:
# Create SQLite database file
conn = sqlite3.connect("C:/Users/yuvan/OneDrive/Desktop/ML_projects/Marketing_campaign_analysis/data/marketing_analytics.db")
cursor = conn.cursor()

In [3]:
df = pd.read_csv("C:/Users/yuvan/OneDrive/Desktop/ML_projects/Marketing_campaign_analysis/data/marketing_data_segmented.csv")
df.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,Complain,Country,Age,Children,Total_Spend,Total_Purchases,Customer_Tenure_Days,Age_Band,Income_Band,Customer_Segment
0,342199,1985,Graduation,Together,59011.7,1,0,2012-11-17,3,0,...,0,Spain,40,1,69,10,4807,40-49,High,Family Customer
1,8075450,1975,Master,Single,1730.0,1,1,2013-04-10,96,0,...,0,Spain,50,2,39,3,4663,50-59,Low,Family Customer
2,13664263,1978,Graduation,Married,98584.6,0,0,2014-01-11,99,920,...,0,Australia,47,0,1512,9,4387,40-49,Very High,High Income
3,16164787,1976,Graduation,Married,74031.5,1,0,2014-06-18,47,265,...,0,Spain,49,1,478,15,4229,40-49,High,Family Customer
4,15815139,1981,Graduation,Divorced,52784.2,1,1,2014-05-20,0,30,...,0,Canada,44,2,330,8,4258,40-49,Mid,High Web Engagement

In [6]:
df.columns

Index(['ID', 'Year_Birth', 'Education', 'Marital_Status', 'Income', 'Kidhome',
       'Teenhome', 'Dt_Customer', 'Recency', 'MntWines', 'MntFruits',
       'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts',
       'MntGoldProds', 'NumDealsPurchases', 'NumWebPurchases',
       'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth',
       'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'AcceptedCmp1',
       'AcceptedCmp2', 'Response', 'Complain', 'Country', 'Age', 'Children',
       'Total_Spend', 'Total_Purchases', 'Customer_Tenure_Days', 'Age_Band',
       'Income_Band', 'Customer_Segment'],
      dtype='object')

In [12]:
cursor.execute("DROP TABLE IF EXISTS customers;")
conn.commit()

In [13]:
cursor.execute("""
CREATE TABLE customers (
    ID INTEGER PRIMARY KEY,

    Year_Birth INTEGER,
    Education TEXT,
    Marital_Status TEXT,
    Income REAL,
    Kidhome INTEGER,
    Teenhome INTEGER,
    Dt_Customer TEXT,
    Recency INTEGER,

    MntWines REAL,
    MntFruits REAL,
    MntMeatProducts REAL,
    MntFishProducts REAL,
    MntSweetProducts REAL,
    MntGoldProds REAL,

    NumDealsPurchases INTEGER,
    NumWebPurchases INTEGER,
    NumCatalogPurchases INTEGER,
    NumStorePurchases INTEGER,
    NumWebVisitsMonth INTEGER,

    AcceptedCmp1 INTEGER,
    AcceptedCmp2 INTEGER,
    AcceptedCmp3 INTEGER,
    AcceptedCmp4 INTEGER,
    AcceptedCmp5 INTEGER,
    Response INTEGER,

    Complain INTEGER,
    Country TEXT,

    Age INTEGER,
    Children INTEGER,
    Total_Spend REAL,
    Total_Purchases INTEGER,
    Customer_Tenure_Days INTEGER,

    Age_Band TEXT,
    Income_Band TEXT,
    Customer_Segment TEXT
);
""")

conn.commit()

In [14]:
df.to_sql("customers", conn, if_exists="append", index=False)

55440

In [15]:
pd.read_sql("SELECT COUNT(*) FROM customers", conn)

   COUNT(*)
0     55440